# Generated by Django 2.2 on 2019-12-04 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='companies_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='products_photos/')),
                ('schooltype', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'praktijkonderwijs'), (2, 'vmbo'), (3, 'mbo'), (4, 'hbo'), (5, 'opleidingsbedrijf')], default=1)),
                ('price', models.FloatField()),
                ('expiration_date', models.DateField(auto_now_add=True, db_index=True)),
                ('categories', models.ManyToManyField(related_name='categories', to='main.Category')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Company')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
