# Generated by Django 2.2 on 2019-12-04 09:28

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191204_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to='companies_logos/'),
        ),
    ]
